name: Deploy Privacy Policy to GitHub Pages

on:
  push:
    branches:
      - main  # Или другая основная ветка
  
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Rename file to match desired URL
        run: mv PRIVACY_POLICY.html policy-privacy.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: policy-privacy.html  # Публикуем файл с нужным именем

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
